### ISSUE TITLE
给开源项目增加描述

### ISSUE THREAD

**Issue by xavieryao** [tuna/mirror-web#39]
Hi 各位，

现在 mirror-web 已经可以在鼠标放上去的时候为每个项目显示简介了。

当前进度：

- [x] AOSP - mysql
- [ ] neurodebian - remi
- [x] repo-ck - virtualbox

需要一些同学来给项目加上简介,方法如下：

0. fork if necessary

1. clone 项目
```bash
git clone https://github.com/tuna/mirror-web.git
```
2. 修改 `_config.yml`
```yaml
descriptions:
  AOSP: 'Android Open Source Project'
  AUR: 'To be filled'
```
3. commit 并发起 pull request, if necessary
<img width="385" alt="2016-11-13 3 10 16" src="https://cloud.githubusercontent.com/assets/2821051/20244212/50255bd0-a9b3-11e6-827a-76754e8cb516.png">
